version: '2'

services:
  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: mypass
    networks:
      - default
  web:
    build: .
    volumes:
      - '.:/opt/app'
    environment:
      SECRET_KEY_BASE: abcdefg
      RAILS_ENV: development
      POSTGRES_PASSWORD: mypass
      PORT: 3000
    ports:
      - "80:3000"
    depends_on:
      - db
    networks:
      - default

networks:
  default:
    driver: bridge